[package]
name = "network-time-pester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
ntp-proto = { version = "1.1.0-alpha.20231123", features = ["__internal-api", "ntpv5"] }
